# Generated by Django 4.1 on 2022-08-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/portfolio.jpeg', upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
